build_bl: error out if we aren't in a ROM directory
Signed-off-by: shagbag913 <sh4gbag913@gmail.com>

diff --git a/.bin/build_bl b/.bin/build_bl
--- a/.bin/build_bl
+++ b/.bin/build_bl
@@ -1,5 +1,11 @@
 #!/usr/bin/env bash
 
+# make sure we're in a ROM directory
+if [[ ! -d frameworks/base ]]; then
+    echo "You must be in the ROM directory! Aborting.."
+    exit 1
+fi
+
 # function to only notify if notifications are enabled
 tg_notify() {
     [[ -z $NOTIFY ]] && return 0
